# 激活开发环境配置
spring:
  profiles:
    active: dev
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT配置
jwt:
  secret: tourSaasSecretKey
  expiration: 86400

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.toursaas.entity